### ISSUE TITLE
Pinning is lost on refreshes or click to same page

### ISSUE THREAD

**Issue by phep** [jayesh-bhoot/pin-unpin-tab#16]
Hi,
Thank you for this nice add-on.
It would be nice if a pinned tab would not become unpinned when refreshed.
And also when the click is to the same page. For example you pin the tab of a ticket in some bug tracker, add a comment to the ticket, and alas the tab is now unpinned :-/.
Ideally this might be configurable in the addon preferences ;-).
Thanks in advance and eager to make tests if you agree with this feature.
phep

**Comment by jayesh-bhoot** [comment]
I haven't been able to reproduce this issue. Could you demonstrate it somehow?

**Comment by phep** [comment]
Hi,

Sorry for being really so late to reply. Here are some (hopefully) reproducible steps for both problems.

**Pinned status lost on refresh**

1. pin some tab
2. refresh tab

**Pinned status lost on edits**

1. Go to Trac issue tracker demo : https://trac.edgewall.org/demo-1.4/wiki/WikiStart
2. pin tab
3. Click on the Edit button at the bottom of the page
4. Edit page of cancel

In both cases one would expect the page to be still pinned after last step, but this is not the case.

Incidentally, I just had a look at how the addon deals with wiki pages. I tried on both Wikipedia and some Dokuwiki instance. I noticed that if you

1. pin a wiki page
2. click on the "Edit" button

a new tab is opened and the original is left unchanged. Well, unless you refresh it after validating your edits in the second tab, but in this case we're back at the first use case of this comment ;-). I cannot deny there is some logic in this precise behaviour, but I have to admit that I would prefer that one could edit wiki pages "in place". Yet I understand that it would be a difficult task to differentiate between `?action=edit` or `?do=edit` and `?length=10&height=5` urls...

Hope this helps,

phep

**Comment by jayesh-bhoot** [comment]
v4 should fix these issues. If not, then feel free to reopen.

**Comment by phep** [comment]
Hi,
Unfortunately the issue is still present on version 4.1.

**Comment by phep** [comment]
Just one more precision. While nothing changed using FF 78 ESR on Linux/Debian, the first use case (pinning lost on refresh) seems to have vanished on FF 84 on Mac OS.
Unfortunately, the second use case (pinning lost on edits) is still present on FF 84 / Mac OS, albeit the tab now appears as pinned (with just the icon) but it is not : clicking on a link open the link in this apparently pinned tab.

**Comment by jayesh-bhoot** [comment]
@phep Okay. I wouldn't bet on this add-on working on ESR version. While I understand it's an ESR version, I don't have the time or motivation to maintain the add-on for it. Sorry about that.

For the second use case, I am out of ideas at this moment. But I intend to pick this up again in near future.

**Comment by jayesh-bhoot** [comment]
@phep let me know if v4.2 fixes these issues for you.
